runtime: nodejs12
service: "friendly-ventures"

instance_class: F1
automatic_scaling:
  max_instances: 1

entrypoint: "PORT=8080 react-scripts start"
handlers:
  - url: /css
    static_dir: build/css

  - url: /images
    static_dir: build/images

  - url: /js
    static_dir: build/js

  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)

  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
